apiVersion : apps/v1
kind: Deployment
metadata:
  name: image
  namespace: test  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image
  template:
    metadata:
      labels:
        app: image 
    spec:
      containers:
        - name: image 
          image: archithacr.azurecr.io/dockerimage
          ports:
          - containerPort: 80
